export {
  type Course,
  coursesTable,
  type Holiday,
  holidaysTable,
  type InsertCourse,
  type InsertHoliday,
  type InsertSection,
  type InsertSectionInstructor,
  type InsertSectionSchedule,
  type InsertTerm,
  type Section,
  type SectionDelivery,
  type SectionInstructor,
  type SectionInstructorRole,
  type SectionSchedule,
  type SectionStatus,
  sectionDeliveryEnum,
  sectionInstructorRoleEnum,
  sectionInstructorsTable,
  sectionSchedulesTable,
  sectionStatusEnum,
  sectionsTable,
  type Term,
  type TermStatus,
  termStatusEnum,
  termsTable,
} from "@/modules/academics/schema";
export {
  type AuditLog,
  auditLogsTable,
  type InsertAuditLog,
} from "@/modules/audit/schema";
export {
  type Enrollment,
  type EnrollmentSource,
  type EnrollmentStatus,
  enrollmentSourceEnum,
  enrollmentStatusEnum,
  enrollmentsTable,
  type InsertEnrollment,
} from "@/modules/enrollment/schema";
export {
  type FileDelivery,
  type FilePurpose,
  type FileRecord,
  type FileStatus,
  fileDeliveryEnum,
  filePurposeEnum,
  fileStatusEnum,
  filesTable,
  type InsertFileRecord,
  type StorageReadRecord,
  storageReadsTable,
} from "@/modules/files/schema";
export {
  type IdempotencyRecord,
  type InsertIdempotencyRecord,
  idempotencyKeysTable,
} from "@/modules/idempotency/schema";
export {
  accountTable,
  type Invitation,
  invitationsTable,
  type PasswordResetLink,
  type Profile,
  type ProfileStatus,
  passwordResetLinksTable,
  profileStatusEnum,
  profilesTable,
  type Role,
  rateLimitTable,
  roleEnum,
  type Session,
  sessionTable,
  twoFactorTable,
  type User,
  userTable,
  verificationTable,
} from "@/modules/identity/schema";
export {
  type InsertJob,
  type Job,
  type JobStatus,
  jobStatusEnum,
  jobsTable,
} from "@/modules/jobs/schema";
export {
  type InsertNotification,
  type InsertNotificationDelivery,
  type InsertNotificationPreference,
  type InsertNotificationUserSettings,
  type Notification,
  type NotificationCategory,
  type NotificationChannel,
  type NotificationDelivery,
  type NotificationDeliveryKind,
  type NotificationDeliveryStatus,
  type NotificationPreference,
  type NotificationUserSettings,
  notificationCategoryEnum,
  notificationChannelEnum,
  notificationDeliveriesTable,
  notificationDeliveryKindEnum,
  notificationDeliveryStatusEnum,
  notificationPreferencesTable,
  notificationsTable,
  notificationUserSettingsTable,
} from "@/modules/notifications/schema";
export {
  type InsertRateLimitsRecord,
  type RateLimitsRecord,
  rateLimitsTable,
} from "@/modules/rate-limit/schema";
export {
  type BrandingConfig,
  brandingSchema,
  type FlagsConfig,
  flagsSchema,
  type InsertSettings,
  lmsSchema,
  type PoliciesConfig,
  policiesSchema,
  type Settings,
  settingsTable,
} from "@/modules/settings/schema";
export {
  type InsertWebhookEvent,
  type WebhookEvent,
  webhookEventsTable,
} from "@/modules/webhooks/schema";
export * from "./_shared";
