import fs from "node:fs";
import path from "node:path";
import {
  PERMISSIONS,
  type Permission,
  ROLE_PERMISSIONS,
} from "../src/lib/authz/permissions";
import type { Role } from "../src/modules/identity/schema";

const ROLES: Role[] = [
  "super_admin",
  "admin",
  "registrar",
  "faculty",
  "student",
];

function getScopeDescription(role: Role, permission: Permission): string {
  const allowed = ROLE_PERMISSIONS[role]?.includes(permission);
  if (!allowed) {
    return "-";
  }

  if (role === "super_admin" || role === "admin" || role === "registrar") {
    return "college-wide";
  }

  if (role === "faculty") {
    if (
      permission.startsWith("assignment:") ||
      permission.startsWith("attendance:") ||
      permission === "grade:submit" ||
      permission === "section:read" ||
      permission === "section:update"
    ) {
      return "instructor-of-section";
    }
    if (permission === "user:read" || permission === "upload:create") {
      return "self";
    }
    return "college-wide";
  }

  if (role === "student") {
    if (
      permission === "assignment:submit" ||
      permission === "assignment:read" ||
      permission === "grade:read" ||
      permission === "attendance:read" ||
      permission === "section:read"
    ) {
      return "enrolled-in-section (self)";
    }
    if (permission === "upload:create") {
      return "self";
    }
    return "college-wide";
  }

  return "college-wide";
}

function generateMarkdown(): string {
  const lines: string[] = [];

  lines.push("# Permissions and Scopes Matrix");
  lines.push("");
  lines.push(
    "> This file is auto-generated by `scripts/gen-permissions-doc.ts`. Do not edit manually.",
  );
  lines.push("");
  lines.push("## Overview");
  lines.push("");
  lines.push(
    "Authorization in the LMS requires passing two distinct checks on every protected action:",
  );
  lines.push(
    "1. **Role Permission**: The actor's assigned roles must include the specified `resource:action` permission.",
  );
  lines.push(
    "2. **Relationship Scope**: The actor must satisfy the relationship scope constraint (e.g., college-wide, instructor of section, enrolled in section, or self).",
  );
  lines.push("");
  lines.push("### Scopes");
  lines.push("");
  lines.push(
    "- `college-wide`: Applies across the entire college organization. Granted to administrators and registrars.",
  );
  lines.push(
    "- `instructor-of-section`: Confined to sections the faculty member is assigned to teach.",
  );
  lines.push(
    "- `enrolled-in-section`: Confined to sections where the student is actively enrolled.",
  );
  lines.push(
    "- `self`: Confined strictly to resources owned by or targeting the authenticated user.",
  );
  lines.push("");
  lines.push("## Matrix Table");
  lines.push("");

  // Table header
  const header = `| Permission | ${ROLES.join(" | ")} |`;
  const separator = `| :--- | ${ROLES.map(() => ":---").join(" | ")} |`;
  lines.push(header);
  lines.push(separator);

  // Table rows
  for (const permission of PERMISSIONS) {
    const cells = ROLES.map((role) => getScopeDescription(role, permission));
    lines.push(`| \`${permission}\` | ${cells.join(" | ")} |`);
  }

  lines.push("");
  return lines.join("\n");
}

function main() {
  const docPath = path.resolve(process.cwd(), "docs/PERMISSIONS.md");
  const content = generateMarkdown();
  fs.writeFileSync(docPath, content, "utf8");
  console.log(`✓ Permissions matrix successfully generated at ${docPath}`);
}

main();
